name: creating-new-env
on:
  workflow_dispatch:
    inputs:
      # Change this value
      environment_name:
        description: 'name of the environment to worked on from Power Platform'
        required: true
        default: TestDev
       #Do Not change these values
      
      
      
env:
#edit your values here
  CLIENT_ID: '76e1074e-e126-4b65-83fa-c043b039ca27'
  TENANT_ID: 'cd41dae2-7921-4c3a-a9a3-56161d080b65'

jobs:
  create-new-env:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: create-environment
      uses: microsoft/powerplatform-actions/create-environment@v0
      with:
        
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{secrets.POWERPLATFORMSECRET}}
        tenant-id: ${{env.TENANT_ID}}
        name: ${{github.event.inputs.environment_name}}
        region: "india"
        currency: "INR"
        type: "Trial"
        
  
